---
title: 'POL290'
subtitle: Grad civil wars seminar.
summary: Grad civil wars seminar.
authors:
- admin
tags:
- teaching
categories: []
date: "2022-02-18"
lastmod: "`r format(Sys.time(), '%d %B, %Y')`"
featured: false
draft: false
bibliography: /Users/juan/Dropbox/github/whistle2/master.bib
csl: /Users/juan/Dropbox/websites/tellez-distill/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    toc: true
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = FALSE, message = FALSE)

library(tidyverse)
library(lubridate)

# function to deal with week dates (from steve miller)
advdate <- function(obj, adv) {
 tmon <- obj + 7*(adv-1)
 tmp <- paste("Week", adv, "--", month(tmon, label = TRUE), day(tmon), ":")
 return(tmp)
}

# first day of the quarter
mon = ymd("2022-03-29")
```


# Course information


<i class="fas fa-user-graduate"></i> Juan Tellez (pronounced: "Teh-yes")

<i class="fas fa-envelope"></i> [jftellez@ucdavis.edu](mailto:jftellez@ucdavis.edu)

<i class="fas fa-clock"></i> Tuesdays, 9:00 AM - 11:50 AM

<i class="fas fa-home"></i> Kerr Hall 594


# Course description


This course is a graduate seminar on the study of political violence. The course will balance developing a background in classic texts while acquiring exposure to work at the frontier of research on violence. 



# Assignments


* Weekly comments (10 percent): Each week you will post (at most) a half page of questions or bullet points comments on the readings. You can raise questions about theory, method, point out conflicts between readings, develop links with previous weeks’ readings, whatever. These needn’t be long and detailed, but they should be thoughtful. Due by XXX. 

* Two article reviews (30 percent): You will write two, three-page (or so, single-spaced) reviews. Your review should eschew summary in favor of critically evaluating the paper. The basic goal is to make a recommendation to an editor (me in this case) as to whether or not the paper should be published; note that these are the JMPs of recent PhDs who did well on the job market. Please review two two of these three papers: 
    * "They're still here, he's all gone: American Fatalities in Foreign Wars and Right-Wing Radicalization at Home"
    * "More than money: The political consequences of compensation"
    * "The Legacies of Atrocities and Who Fights"

* Research proposal (30 percent): 12 pages. See rubric. Due on XXX.


* Data exploration (10 percent): You will provide exploratory data analysis of a dataset or replication file of your choice. Basic descriptives, visualize patterns, temporal and spatial limitations, approaches to merging with other datasets. You will turn in: cleaned dataset (.rds) and an Rmarkdown file to reproduce analysis. 




# Schedule




## `r advdate(mon, 1)`: What is civil war? 


### Required

* [@kalyvas:balcells:2010]
* [@blattman:miguel:2010]
* [@sambanis:2004]
* [@kalyvas:straus:2020]


### Recommended


## `r advdate(mon, 2)` Causes of civil war


### Required

* [@fearon:laitin:2003]
* [@cederman:etal:2011]
* [@collier:hoeffler:2004]
* [@carter:etal:2019]


## `r advdate(mon, 3)` Political economy of conflict


### Required

* [@dube:vargas:2013]
* [@dalbo:dalbo:2011]
* [@sanchez:2020]

## `r advdate(mon, 4)` Rebel groups as organizations

### Required

* [@weinstein:2007]
* [@parkinson:2013]
* [@arjona:2016]


## `r advdate(mon, 5)` Dynamics of violence in civil wars

### Required

* [@kalyvas:2006]
* [@condra:etal:2018]


## `r advdate(mon, 6)` Civil war duration and termination

* [@mattes:savun:2010]
* [@cunningham:2006]
* [@toft:2010]


## `r advdate(mon, 7)` Wartime displacement and return

* [@steele:2017]
* [@mcnamee:2018]


## `r advdate(mon, 8)` Peacekeeping and peacebuilding

* [@walter:etal:2021]
* [@matanock:2017]


## `r advdate(mon, 9)` Political and social consequences of war

* [@bauer:etal:2016]


## `r advdate(mon, 10)` Presentations
